package io.github.docflowlib.docflow.annotations;

import org.springframework.http.HttpStatus;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Customizes the OpenAPI documentation generated by Docflow for a specific endpoint.
 * <p>
 * This annotation allows developers to fine-tune the automated documentation.
 * For example, you can exclude specific HTTP status codes that Docflow would
 * normally inject by default.
 * <p>
 * <b>Example usage:</b>
 * <pre>
 * &#64;DeleteMapping("/{id}")
 * &#64;ApiDoc(exclude = {HttpStatus.NOT_FOUND})
 * public ResponseEntity&lt;Void&gt; delete(@PathVariable Long id) {
 *     // Deletion logic...
 *     return ResponseEntity.noContent().build();
 * }
 * </pre>
 *
 * @since 2.0.0
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface ApiDoc {

    /**
     * Specifies the HTTP status codes automatically generated by DocFlow that should be excluded from the documentation.
     *
     * @return an array of {@link HttpStatus} to be ignored.
     */
    HttpStatus[] exclude() default {};
}
